services:

  backend:
    build: ./backend
    container_name: backend_server
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/gig-docker
    depends_on:
      - mongo
      - redis

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
  mongo:
    image: mongo:7
    container_name: docker_mongo
    command: >
      mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7
    container_name: docker_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
volumes:
  mongo_data:
  redis_data: